### ISSUE TITLE
"Bogazici University" as my email address. 

### ISSUE THREAD

**Issue by tasomaniac** [Garaj/garaj-webapp#1]
I got the following problem today. Here is the log. 

![screen shot 2015-07-16 at 17 33 26](https://cloud.githubusercontent.com/assets/763339/8726130/f41f5a9e-2be0-11e5-99e2-07feffe239c0.png)

And Chrome remembers the input fields and it somehow puts "Bogazici University" again in the email field.

**Comment by demircancelebi** [comment]
I do not really get the problem here. Why Chrome puts "Bogazici University" to the email field?

**Comment by tasomaniac** [comment]
Here is the screenshot. 

![screen shot 2015-07-18 at 12 05 13](https://cloud.githubusercontent.com/assets/763339/8761037/46e5d4aa-2d45-11e5-8ea9-b64dd34b11b8.png)

**Comment by tasomaniac** [comment]
I think it was because of a change in an id of a field. 
I've deleted the password in Chrome's settings and the issue is gone. 
Will reopen it if I see the problem again.
