### ISSUE TITLE
New blog post not editable

### ISSUE THREAD

**Issue by tasomaniac** [Garaj/garaj-webapp#2]
I cannot input text into Post body field. 

![screen shot 2015-07-16 at 17 35 03](https://cloud.githubusercontent.com/assets/763339/8726147/14dac638-2be1-11e5-86cf-2e4041db50fa.png)

**Comment by demircancelebi** [comment]
Thanks for the report!

f00f09a793b9ec7a44a94c1c73b4dfd221611248 fixed this, closing issue.
