### ISSUE TITLE
Markdown support for blog posts :)

### ISSUE THREAD

**Issue by tasomaniac** [Garaj/garaj-webapp#3]
We can just discuss this here. :)

**Comment by demircancelebi** [comment]
It would be delightful.
Do you know any WYSIWYG editor with markdown support. We use 'medium-editor' for the moment.

**Comment by tasomaniac** [comment]
I think medium editor is really good and enough. Don't need markdown
support.

**Comment by demircancelebi** [comment]
Closing the issue then.
